[package]
name = "solar-data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
openapi = { path = "./openapi" }
serde = { version = "1.0.131", features = [ "derive" ] }
thiserror = "1"
tokio = { version = "1.0", features = [ "full" ] }
toml = "0.5.8"
reqwest = "0.11"
