/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnergyLifetimeResponse {
    /// When no `start_date` parameter is specified on the request, this is the `operational_date` of the system. May be null if system has never produced. When a `start_date` parameter is included in the request, it is included here in the response.
    #[serde(rename = "start_date")]
    pub start_date: String,
    /// The identifier of the system.
    #[serde(rename = "system_id")]
    pub system_id: i32,
    /// An array of production measurements, one for each day since the system started producing, or one for each day of the requested period. If the system has never produced energy, the array may be empty.
    #[serde(rename = "production")]
    pub production: Vec<i32>,
    #[serde(rename = "micro_production", skip_serializing_if = "Option::is_none")]
    pub micro_production: Option<Vec<i32>>,
    #[serde(rename = "meter_production", skip_serializing_if = "Option::is_none")]
    pub meter_production: Option<Vec<i32>>,
    /// The first day in the time series when measurements are taken from a meter instead of from microinverters. This field is not present unless the system has a meter.
    #[serde(rename = "meter_start_date", skip_serializing_if = "Option::is_none")]
    pub meter_start_date: Option<String>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::Meta>,
}

impl EnergyLifetimeResponse {
    pub fn new(start_date: String, system_id: i32, production: Vec<i32>, meta: crate::models::Meta) -> EnergyLifetimeResponse {
        EnergyLifetimeResponse {
            start_date,
            system_id,
            production,
            micro_production: None,
            meter_production: None,
            meter_start_date: None,
            meta: Box::new(meta),
        }
    }
}


