/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvertersSummaryByEnvoyOrSiteResponse {
    #[serde(rename = "signal_strength")]
    pub signal_strength: i32,
    /// A list of active inverters on this system, including serial and model numbers.
    #[serde(rename = "micro_inverters")]
    pub micro_inverters: Vec<crate::models::InvertersSummaryByEnvoyOrSiteResponseMicroInverters>,
}

impl InvertersSummaryByEnvoyOrSiteResponse {
    pub fn new(signal_strength: i32, micro_inverters: Vec<crate::models::InvertersSummaryByEnvoyOrSiteResponseMicroInverters>) -> InvertersSummaryByEnvoyOrSiteResponse {
        InvertersSummaryByEnvoyOrSiteResponse {
            signal_strength,
            micro_inverters,
        }
    }
}


