/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Meta : Information about the system that you can use to ascertain the timeliness of the production data included in the response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Meta {
    #[serde(rename = "status")]
    pub status: crate::models::Status,
    #[serde(rename = "last_report_at")]
    pub last_report_at: i64,
    #[serde(rename = "last_energy_at")]
    pub last_energy_at: i64,
    #[serde(rename = "operational_at")]
    pub operational_at: i64,
}

impl Meta {
    /// Information about the system that you can use to ascertain the timeliness of the production data included in the response.
    pub fn new(status: crate::models::Status, last_report_at: i64, last_energy_at: i64, operational_at: i64) -> Meta {
        Meta {
            status,
            last_report_at,
            last_energy_at,
            operational_at,
        }
    }
}


