/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonthlyProductionResponse {
    /// Enlighten ID for this system.
    #[serde(rename = "system_id")]
    pub system_id: i32,
    /// First day included in the reporting period. The format is `YYYY-mm-dd` unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
    #[serde(rename = "start_date")]
    pub start_date: String,
    /// Last day included in the reporting period.
    #[serde(rename = "end_date")]
    pub end_date: String,
    /// Total production for the requested period in Watt-hours.
    #[serde(rename = "production_wh")]
    pub production_wh: i32,
    /// If the system has any revenue-grade meters installed, the meter readings at the beginning and end of the reporting period are included here. Otherwise, the array is empty.
    #[serde(rename = "meter_readings")]
    pub meter_readings: Vec<crate::models::MonthlyProductionResponseMeterReadings>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::Meta>,
}

impl MonthlyProductionResponse {
    pub fn new(system_id: i32, start_date: String, end_date: String, production_wh: i32, meter_readings: Vec<crate::models::MonthlyProductionResponseMeterReadings>, meta: crate::models::Meta) -> MonthlyProductionResponse {
        MonthlyProductionResponse {
            system_id,
            start_date,
            end_date,
            production_wh,
            meter_readings,
            meta: Box::new(meta),
        }
    }
}


