/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonthlyProductionResponseMeterReadings {
    #[serde(rename = "serial_number")]
    pub serial_number: String,
    #[serde(rename = "start")]
    pub start: i32,
    #[serde(rename = "end")]
    pub end: i32,
}

impl MonthlyProductionResponseMeterReadings {
    pub fn new(serial_number: String, start: i32, end: i32) -> MonthlyProductionResponseMeterReadings {
        MonthlyProductionResponseMeterReadings {
            serial_number,
            start,
            end,
        }
    }
}


