/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductionMeterReadingsResponse {
    #[serde(rename = "system_id")]
    pub system_id: i32,
    #[serde(rename = "meter_readings")]
    pub meter_readings: Vec<crate::models::ProductionMeterReadingsResponseMeterReadings>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::Meta>,
}

impl ProductionMeterReadingsResponse {
    pub fn new(system_id: i32, meter_readings: Vec<crate::models::ProductionMeterReadingsResponseMeterReadings>, meta: crate::models::Meta) -> ProductionMeterReadingsResponse {
        ProductionMeterReadingsResponse {
            system_id,
            meter_readings,
            meta: Box::new(meta),
        }
    }
}


