/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RgmStatsResponseIntervals1 {
    /// The reporting channel identifier.
    #[serde(rename = "channel")]
    pub channel: i32,
    /// End of interval. The format is Unix epoch time unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
    #[serde(rename = "end_at")]
    pub end_at: i64,
    /// Energy delivered during this interval, in Watt-hours.
    #[serde(rename = "wh_del")]
    pub wh_del: Option<f32>,
    /// Energy delivered during this interval, in Watts.
    #[serde(rename = "curr_w")]
    pub curr_w: Option<i32>,
}

impl RgmStatsResponseIntervals1 {
    pub fn new(channel: i32, end_at: i64, wh_del: Option<f32>, curr_w: Option<i32>) -> RgmStatsResponseIntervals1 {
        RgmStatsResponseIntervals1 {
            channel,
            end_at,
            wh_del,
            curr_w,
        }
    }
}


