/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponseIntervals {
    /// End date for interval. The format is Unix epoch time unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
    #[serde(rename = "end_at")]
    pub end_at: i64,
    /// Average power produced by microinverters during this interval, in Watts.
    #[serde(rename = "powr")]
    pub powr: i32,
    /// Energy produced by microinverters during this interval, in Watt-hours.
    #[serde(rename = "enwh")]
    pub enwh: i32,
    /// Number of microinverters that reported data for this interval at the time of the request.
    #[serde(rename = "devices_reporting")]
    pub devices_reporting: i32,
}

impl StatsResponseIntervals {
    pub fn new(end_at: i64, powr: i32, enwh: i32, devices_reporting: i32) -> StatsResponseIntervals {
        StatsResponseIntervals {
            end_at,
            powr,
            enwh,
            devices_reporting,
        }
    }
}


