/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnprocessableEntityError {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "errorMessages", skip_serializing_if = "Option::is_none")]
    pub error_messages: Option<Vec<String>>,
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<i32>,
    #[serde(rename = "end_at", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<i32>,
    #[serde(rename = "first_interval", skip_serializing_if = "Option::is_none")]
    pub first_interval: Option<i32>,
    #[serde(rename = "last_interval", skip_serializing_if = "Option::is_none")]
    pub last_interval: Option<i32>,
}

impl UnprocessableEntityError {
    pub fn new() -> UnprocessableEntityError {
        UnprocessableEntityError {
            reason: None,
            message: None,
            error_messages: None,
            start: None,
            end: None,
            start_at: None,
            end_at: None,
            first_interval: None,
            last_interval: None,
        }
    }
}


