/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConflictError {
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "message")]
    pub message: Vec<String>,
    #[serde(rename = "period")]
    pub period: Period,
    #[serde(rename = "period_start")]
    pub period_start: i32,
    #[serde(rename = "period_end")]
    pub period_end: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl ConflictError {
    pub fn new(reason: String, message: Vec<String>, period: Period, period_start: i32, period_end: i32, limit: i32) -> ConflictError {
        ConflictError {
            reason,
            message,
            period,
            period_start,
            period_end,
            limit,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Period {
    #[serde(rename = "hour")]
    Hour,
    #[serde(rename = "minute")]
    Minute,
    #[serde(rename = "second")]
    Second,
}

