/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConnectionType : How the system is connected to the Internet.

/// How the system is connected to the Internet.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectionType {
    #[serde(rename = "ethernet")]
    Ethernet,
    #[serde(rename = "cellular")]
    Cellular,
    #[serde(rename = "wifi")]
    Wifi,

}

impl ToString for ConnectionType {
    fn to_string(&self) -> String {
        match self {
            Self::Ethernet => String::from("ethernet"),
            Self::Cellular => String::from("cellular"),
            Self::Wifi => String::from("wifi"),
        }
    }
}




