/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsumptionLifetimeResponse {
    /// When no `start_date` parameter is specified on the request, this is the `operational_date` of the system. May be null if system has never produced. When a `start_date` parameter is included in the request, it is included here in the response.
    #[serde(rename = "start_date")]
    pub start_date: String,
    /// The identifier of the system.
    #[serde(rename = "system_id", skip_serializing_if = "Option::is_none")]
    pub system_id: Option<i32>,
    /// An array of consumption measurements, one for each day since consumption metering began, or one for each day of the requested period.
    #[serde(rename = "consumption")]
    pub consumption: Vec<i32>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::Meta>,
}

impl ConsumptionLifetimeResponse {
    pub fn new(start_date: String, consumption: Vec<i32>, meta: crate::models::Meta) -> ConsumptionLifetimeResponse {
        ConsumptionLifetimeResponse {
            start_date,
            system_id: None,
            consumption,
            meta: Box::new(meta),
        }
    }
}


