/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvoysResponse {
    /// The identifier of the system.
    #[serde(rename = "system_id")]
    pub system_id: i32,
    /// A list of active Envoys on this system.
    #[serde(rename = "envoys")]
    pub envoys: Vec<crate::models::EnvoysResponseEnvoys>,
}

impl EnvoysResponse {
    pub fn new(system_id: i32, envoys: Vec<crate::models::EnvoysResponseEnvoys>) -> EnvoysResponse {
        EnvoysResponse {
            system_id,
            envoys,
        }
    }
}


