/*
 * The Enlighten Systems API
 *
 * The Enlighten Systems API is a JSON-based API that provides access to performance data for a PV system. By using the Enlighten Systems API, you agree to the Enphase Energy API License Agreement.  Please note that the Enlighten Systems API does not provide performance data at a panel or microinverter level.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RgmStatsResponseIntervals {
    /// End of interval. The format is Unix epoch time unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
    #[serde(rename = "end_at")]
    pub end_at: i64,
    /// Energy delivered during this interval, in Watt-hours.
    #[serde(rename = "wh_del")]
    pub wh_del: i32,
    /// Number of revenue-grade meters that reported data for this interval at the time of the request.
    #[serde(rename = "devices_reporting")]
    pub devices_reporting: i32,
}

impl RgmStatsResponseIntervals {
    pub fn new(end_at: i64, wh_del: i32, devices_reporting: i32) -> RgmStatsResponseIntervals {
        RgmStatsResponseIntervals {
            end_at,
            wh_del,
            devices_reporting,
        }
    }
}


